public enum TypeAbility
{
    DamageAmplifier,
    ArmorAmplifier,
    MoveSpeedAmplifier,
    RegenerationAmplifier,
    Healing,
    AttackAbility,
    PassiveAbility,
    Summon,
    ThrowAxe,
    JerkFront,
    Rage,
    Epiphany,
    ShieldUp,
    SoulExplosion,
    DarkPact,
    StunningBlow
}